### ISSUE TITLE
npm @types/command-line-usage

### ISSUE THREAD

**Issue by matrumz** [75lb/command-line-usage#16]
command-line-commands and command-line-args have support for @types/ in NPM: can this get type definition files added as well?

**Comment by 75lb** [comment]
i don't use Typescript, I don't know where to start with this ticket.. what exactly are you asking for? Can you give me an example of what would solve this issue?

**Comment by matrumz** [comment]
Ah, I see that someone else created the types for command-line-commands/args. 

If you're interested in learning and doing it, you can check out their work here: [DefinitelyTyped:command-line-commands](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/command-line-commands)

Otherwise, you can assign it to me and I should be able to get to it in the next few weeks.

**Comment by 75lb** [comment]
feel free to publish TS typings but I have no plans to include them as part of this module.. they belong in separate module.
