### ISSUE TITLE
Support for coloured text

### ISSUE THREAD

**Issue by Niels-NTG** [75lb/command-line-usage#2]
Would be nice to have support for simple inline text color. Something like this:
```
[color=red]{This is some red coloured text.}\n
This is some normal coloured text.\n
[color=cyan]{Some cyan coloured words.}
```

**Comment by 75lb** [comment]
we already have that feature, command-line-usage uses [this method](https://github.com/75lb/ansi-escape-sequences#module_ansi-escape-sequences.format) for inline formatting..  try this:
```
[red]{This is some red coloured text.}\n
This is some normal coloured text.\n
[cyan]{Some cyan coloured words.}
```

**Comment by 75lb** [comment]
it's mentioned in the docs [here](https://github.com/75lb/command-line-usage#usageoptions-)

**Comment by Niels-NTG** [comment]
Wasn't aware of that. Thanks!

**Comment by 75lb** [comment]
you're welcome
