### ISSUE TITLE
How to handle options/commands?

### ISSUE THREAD

**Issue by Bizarrus** [75lb/command-line-usage#20]
I'm misunderstand the handling of these package.

How i can step into registred commands like these:
```js
{
    header:		'Available Commands',
    content: [
      { name: 'check', summary: 'Check a given nickname' },
      { name: 'register', summary: 'Register a nickname with given informations' },
      { name: 'help', summary: 'Display help informations.' },
      { name: 'version', summary: 'Print the version.' },
    ]
  }
```

When i try to use `node main.js check`, on `argv`, each time `help` is present.

**Comment by 75lb** [comment]
hi, i'm sorry for the late reply!

I don't understand what your issue is.. what is `main.js`? `help` is present where?

Please post some example code which I can run and debug.
