### ISSUE TITLE
Feature to print \n \r 

### ISSUE THREAD

**Issue by CarpeDiemKopi** [75lb/command-line-usage#26]
I can do: 
`console.log(JSON.stringify("output with printed  \n and no line break"))`
and get: 
`output with printed  \n and no line break`

I tried:
```
    optionList: [
      { 
        name: 'preload',
        type: Boolean, 
        description: JSON.stringify("initex.js '\n<fmt>' to dump core by with with format fmt"), 
        alias: 'p'
      },
```
and I get a linebreak which I don't want.

I get chaos if do 
`console.log(JSON.stringify("commandline_usage)) `
because all line breaks are removed.

Is there another way to do this?

**Comment by 75lb** [comment]
Try using `\\n` instead of `\n` in your description..

**Comment by CarpeDiemKopi** [comment]
I've tried that before, but it's not working also not with Cmder.
**result:** 
```
  -p, --preload     initex.js '
                    &fmt/n/n' to dump core with format fmt -> tex.js`

```
**due to:** 

```
  {
    header: 'Options',
    optionList: [
      { 
        name: 'preload',
        type: Boolean, 
        description: "initex.js '\\n&fmt/n/n' to dump core with format fmt -> tex.js", 
        alias: 'p'
      },



```
I'm temporarily using slash instead of backslash.

**Comment by 75lb** [comment]
I just tried it myself, for some reason you need four escape characters, e.g. 

```
const sections = [
  {
    header: 'A typical app',
    content: 'A newline: \\\\n. After the newline.'
  }
]
const usage = commandLineUsage(sections)
console.log(usage)
```

This prints: 

```
A typical app

  A newline: \n. After the newline.
```

At some point I'll look into why you need four, but for now this works.
