### ISSUE TITLE
chalk is not working

### ISSUE THREAD

**Issue by CarpeDiemKopi** [75lb/command-line-usage#27]
```
const cliUsage = require('command-line-usage')
const sections = [
  {
    header: 'web2js: compile.js, initex.js, tex.js',
    content: '{underline Generate WebAssembly {bold JSTEs} {italic (JavaScript Typesetting Engines)} and core.dump}'
  },
```
result: 
- underline => OK
- bold => OK
- italic is not working

Why? 

Windows 10 1803 64 bit node v11.10.1, comand-line-usage and chalk just installed.

**Comment by 75lb** [comment]
For some reason, italics does not work by default on windows.. Chalk [recommends cmder](https://github.com/chalk/chalk#windows) - try that.
