### ISSUE TITLE
Missing `name` in README example

### ISSUE THREAD

**Issue by marcoscaceres** [75lb/command-line-usage#3]
Trying to run the example throws with:  
NAME_MISSING: Invalid option definitions: the `name` property is required on each definition

**Comment by marcoscaceres** [comment]
Might be good to actually allow "header" to be a fallback for name? That way, name can be optional if header is present.

**Comment by 75lb** [comment]
Everything is fine with the example code, you have something wrong locally.

**Comment by 75lb** [comment]
sounds like you have command-line-usage v2 installed locally.. the docs on the README are for v3.

**Comment by marcoscaceres** [comment]
Right, let me double check!

**Comment by marcoscaceres** [comment]
(I'm actually in the process of updating the v3, which is what brought me here 😄)

**Comment by marcoscaceres** [comment]
No, definitely on the right version ("command-line-usage": "^3.0.1",)

**Comment by 75lb** [comment]
you have v2 installed somewhere, else you would not be getting these errors..

**Comment by 75lb** [comment]
actually, i see now.. you are running the example code with command-line-args, instead of usage..  if i replace the line at the top with this (notice it loads args), i get your errors: 

```
const getUsage = require('command-line-args')
```

**Comment by marcoscaceres** [comment]
ah, d'oh

**Comment by marcoscaceres** [comment]
@75lb I'm still a bit confused tho, ideally, I would still like to use the same object for command-line-args and for command-line-usage.

**Comment by 75lb** [comment]
the same object is still used..  say your option definitions are: 

```js
const optionDefinitions = [
  {
    name: 'port', alias: 'p', type: Number, defaultOption: true,
    description: 'Web server port.', group: 'server'
  }
]
```

that object is passed to your `optionList` section in the usage: 

```js
const usage = commandLineUsage([
  {
     header: 'Options',
     optionList: optionDefinitions
  }
])
```

**Comment by 75lb** [comment]
i needed to change the usage API to be more flexible, to cater for other use cases and guys using different option parsers.. in v2, the usage template was limited, in v3 you have more control. 

Also, it was necessary for me to completely de-couple args and usage.

**Comment by marcoscaceres** [comment]
yeah, I see that. It's cool. Just means a little re-adjustment. 

Ok, so: "optionDefinitions" is for getUsage() and "optionsList" is for commandLineArgs().

**Comment by marcoscaceres** [comment]
Just for completeness, in case others run into this problem during migration... I ended up with:

```JS
const commandLineArgs = require("command-line-args");
const getUsage = require("command-line-usage");
// Command line output
const optionsList = [{
  alias: "h",
  defaultValue: false,
  description: "Display this usage guide.",
  name: "help",
  type: Boolean,
}, {
  alias: "s",
  defaultOption: true,
  description: "URL to ReSpec source file.",
  multiple: false,
  name: "src",
  type: String,
}, {
  alias: "o",
  defaultOption: false,
  description: "Path to output file. When omitted, just stdout.",
  multiple: false,
  name: "out",
  type: String,
}, {
  alias: "t",
  defaultValue: 10,
  name: "timeout",
  type: Number,
}, {
  alias: "e",
  default: false,
  description: "Report ReSpec errors on stderr.",
  name: "haltonerror",
  type: Boolean,
}, {
  alias: "w",
  default: false,
  description: "Report ReSpec warnings on stderr.",
  name: "haltonwarn",
  type: Boolean,
}];
const optionDefinitions = [{
  header: "respec2html",
  name: "respec2html",
  content: "Converts a ReSpec source file to HTML and prints to std out.",
  footer: "Project home: [underline]{https://github.com/w3c/respec}"
}, {
  header: "Options",
  name: "Options",
  optionsList,
}];

let parsedArgs;
try {
  parsedArgs = commandLineArgs(optionsList);
} catch (err) {
  console.error(err);
  console.log(getUsage(optionDefinitions));
  return process.exit(2);
}
// other stuff... where it's all good :)
```

**Comment by marcoscaceres** [comment]
Wait... don't go all reacting all negative just yet! 😄 ... still cleaning it up!

**Comment by 75lb** [comment]
the bottom half should be like this..

```js
const usageSections = [{
  header: "respec2html",
  content: "Converts a ReSpec source file to HTML and prints to std out.",
}, {
  header: "Options",
  optionsList: optionDefinitions
}, {
  content: "Project home: [underline]{https://github.com/w3c/respec}"
}];

let parsedArgs;
try {
  parsedArgs = commandLineArgs(optionsList);
} catch (err) {
  console.error(err);
  console.log(getUsage(usageSections));
  return process.exit(2);
}
```

**Comment by marcoscaceres** [comment]
Ah, I was just about to ask you about "footer"!

**Comment by 75lb** [comment]
if you want a content section *not* to be indented (as the v2 `footer` field was not indented), set the `raw` flag:  https://github.com/75lb/command-line-usage#commandlineusagecontent.

maybe the v3 docs are not clear enough?

**Comment by marcoscaceres** [comment]
I just hadn't gotten to `raw` yet :) 

This has been super helpful, @75lb! I'll give the docs another read now and see if I can help in some way.
