### ISSUE TITLE
Need a way to have only short optionList names

### ISSUE THREAD

**Issue by SHND** [75lb/command-line-usage#30]
Currently name property in optionList is required and it is rendered with `--` prefix in the usage help text.

I'm trying to create a usage help in which some of the switches doesn't accept long forms and I want to render them like below:
```
  -l value              List all                     
  -f                    force description 
  -a, --append value    Appending some value
```

**Comment by 75lb** [comment]
ok, I'll look into it thanks.. in the meantime you could pass your arbitrary content into [table-layout](https://github.com/75lb/table-layout).. let me know if you need any tips.

**Comment by SHND** [comment]
Awesome, I didn’t know about table-layout. I tried to clear characters on screen using \b for now but it was messing up the layout. 

Btw nice work on the package.

**Comment by 75lb** [comment]
Fixed and released in v6.1.0. Let me know if you find anything else. 👍

**Comment by SHND** [comment]
That sounds great, Thank you. Can you please provide a simple example in this thread?

**Comment by 75lb** [comment]
see [the release notes](https://github.com/75lb/command-line-usage/releases/tag/v6.1.0), sorry I should have linked to them before.

**Comment by SHND** [comment]
It seems that "@types/command-line-usage" needs to be updated for this change.

**Comment by 75lb** [comment]
Sorry, I'm not a typescript user and don't maintain `@types/command-line-usage` - could you submit a PR to DefinitelyTyped and have it fixed?

**Comment by SHND** [comment]
I'm not familiar with how the definition files are being maintained, but I try to look into it when I get a chance. But I definitely encourage to check it out, it's pretty awesome for at least code completion for IDEs and Editors (along with all the cool stuff TypeScript offers).
It seems that some people enjoyed your package that much that they write definitions for it :)
