### ISSUE TITLE
Feature request: allow for table options in regular content blocks

### ISSUE THREAD

**Issue by kwaping** [75lb/command-line-usage#31]
I have a Usage section that is quite wide (15 character `desc` and 80 character `example`). This is creating wrapping issues that are breaking my Jest snapshots when not running in a TTY (Jenkins CI). I have [filed an issue in 75lb/table-layout](https://github.com/75lb/table-layout/issues/9) as well.

I think that both issues could be resolved by allowing `content.js` to work with tableOptions  like you have in `option-list.js`.

Thanks!

**Comment by 75lb** [comment]
Sorry for the slow reply, this is actually already supported but wasn't documented very well.. I updated [this wiki page](https://github.com/75lb/command-line-usage/wiki/How-to-use-advanced-table-formatting#table-layout-in-a-section) to show how it's done..
