### ISSUE TITLE
Markdown formatting for documentation

### ISSUE THREAD

**Issue by ad-m** [75lb/command-line-usage#32]
Hello,

Thank you for the very helpful library. I see her new use case. Well, I'm going to develop documentation using the Markdown format for our extensive CLI.

To this end, support for Markdown formatting would be useful.

I am asking for information in this regard, as well as in the scope of possible incorporation of changes to this library. I prefer to be sure about work on the topic before I start developing my own solution.

Kind regards,

**Comment by 75lb** [comment]
You can see an example of how I format the output for markdown here (click "edit" to see the raw markdown): 
https://github.com/lwsjs/local-web-server/wiki/CLI-usage

Does that help?

**Comment by ad-m** [comment]
Thank you for the quick reply. 

This is the initial approach (I have used it before for testing CLI generator) and it is enough for internal needs to use `code` syntax. However, my goal is to develop Markdown documents that can then be turned into a full-fledged page (using VuePress / Hugo or another static page generator) like https://cloud.google.com/sdk/gcloud/reference or https://docs.aws.amazon.com/cli/latest/reference/#available-services .

In this case, it needs a more markdown-way generation method. As I understand it, there are no ongoing works in this respect and I will have to think about how to approach them myself.

**Comment by ad-m** [comment]
command-line-application already implemenent Markdown formatting: https://github.com/hipstersmoothie/command-line-docs

**Comment by 75lb** [comment]
Have you made an progress with this issue? I don't have any immediate plans to build a markdown generator for CLI documentation, but maybe in the future..
