### ISSUE TITLE
request: allow for "boolean", "number" and "string"

### ISSUE THREAD

**Issue by smashah** [75lb/command-line-usage#33]
Hi, changing this line:

https://github.com/75lb/command-line-usage/blob/94032cfc2bc343b14efb0579529aa50178ae29f3/lib/section/option-list.js#L53

only allows usage of:

```
Boolean
Number
String
```

but changing it to: 

```javascript
let type = typeof definition.type === "string" ? definition.type.toLowerCase() : definition.type ? definition.type.name.toLowerCase() : 'string'
```

would allow the usage of all of these:

```
Boolean
Number
String

"boolean"
"number"
"string"
```

The first three resolves to the second three anyway so it should not break anything.

This would make this library play perfectly with the meow library without any redundant code.

Thanks

**Comment by 75lb** [comment]
Hi, thanks for the suggestion.. There are many other command line parsing libs, not only meow - they come and go.. it's impossible to make this lib play perfectly with them all without some sort of small adapter layer in between..

If you pass the meow `type` field into this lib's `typeLabel` property you should get the behaviour you want..
