### ISSUE TITLE
show default value

### ISSUE THREAD

**Issue by tcurdt** [75lb/command-line-usage#35]
I don't see a way to show the default value.

**Comment by 75lb** [comment]
Hi, the library does not make an assumption how the default value should be displayed - it's up to you.. You can add it to the option description if you like..

**Comment by tcurdt** [comment]
Why not have a placeholder to output the value from the options definition?
Duplicating this manually in the description is cumbersome and error prone.

**Comment by Martin-Office** [comment]
You can automate it this way: [Example](https://gist.githubusercontent.com/Martin-Office/8c1458ac39ca070937a5a7da9715e2e0/raw/68dfe36d31692336c66b0dc48e5ac0ca6794a004/index.js)

**Comment by tcurdt** [comment]
Not a fan. I moved on. But thanks for the pointer.
