### ISSUE TITLE
[request] automatic --help defaults?

### ISSUE THREAD

**Issue by braco** [75lb/command-line-usage#43]
Hi,

Great package!

Let's say you have some default args setup via `commandLineArgs()`.

Why can't a rudimentary --help be automatically generated from that?

Or am I missing something?

**Comment by 75lb** [comment]
command-line-args and command-line-usage are two independent, automous libraries.. neither requires the other, nor depends on the other. One library parses `process.argv` the other prints formatted text based on certain inputs. They are two separate concerns..

**Comment by braco** [comment]
Thanks for the reply. They seem generally coupled to me, one is tracking the schema of the other based on convention, requiring parallel maintenance. It would cover basic use cases if they could communicate, as in export data from args to usage.

https://www.npmjs.com/package/argparse
