### ISSUE TITLE
Upgrade to table-layout v4

### ISSUE THREAD

**Issue by nwalters512** [75lb/command-line-usage#45]
I was happy to see that [`table-layout` v4.0.0](https://github.com/75lb/table-layout/releases/tag/v4.0.0) cleaned up some dependencies. Would you consider upgrading this package to use that new version? That would probably necessitate a major version bump because of the move to drop support for Node versions <16. I'd be happy to make a PR for this if you'd welcome one.

**Comment by 75lb** [comment]
Hi , I'll get back to you tomorrow thanks.. first, once I've checked
everything, I will likely add v12 support back to table-layout so it can be
used in CLU without requiring a major version bump..

**Comment by nwalters512** [comment]
Sounds great! Thanks for the quick reply.

**Comment by 75lb** [comment]
Fixed and released in command-line-usage@7.0.3
